### ISSUE TITLE
Prepare for publication

### ISSUE THREAD

**Issue by constantinpape** [mobie/clem-example-project#1]
What do we need to add to the dataset for publication, i.e. what do we want to demonstrate with it?
I think we should def. add some bookmarks with tomograms.

**Comment by martinschorb** [comment]
I think it would also be great to prepare a step-by-step tutorial on how to get to the exact state of how we publish data in MoBIE.

Probably, we could even include it directly to the git repos for each project and have an automated documentation.

What would be a good format? Jupyter or just something text-based (md->readthedocs/guthub pages or similar)?

**Comment by tischi** [comment]
Probably good to team up with @K-Meech and @vzinche who created this: https://mobie.github.io/

**Comment by constantinpape** [comment]
Yes, I think it would be good to keep the documentation centrally at https://mobie.github.io/.
Also, there is a fairly detailed notebook about the python tools here: https://github.com/mobie/mobie-utils-python/blob/master/examples/create_mobie_project.ipynb.

> Probably, we could even include it directly to the git repos for each project and have an automated documentation.

I am always adding the scripts that are used for data generation to the repository for reproducibility.
But often there are special quirks for the datasets, which don't make these so educational.
Anyway, it can't hurt to document this a bit more in the README; but I think most effort should go to the central documentation.

**Comment by martinschorb** [comment]
Has there been any additional registration step? Has Giulia done this in BigWarp before preparing the MoBIE repo? I am surprised how good this looks and doubt that my converter did such a good job.

For the docs, we could configure the CI such that it pulls the markdown protocol(s) (in a 'doc' sub-directory) from the data repositories and adds it to the central website.

**Comment by constantinpape** [comment]
> Has there been any additional registration step? Has Giulia done this in BigWarp before preparing the MoBIE repo? I am surprised how good this looks and doubt that my converter did such a good job.

I think @tischi knows more about the registration approach because he helped out on this.

> For the docs, we could configure the CI such that it pulls the markdown protocol(s) (in a 'doc' sub-directory) from the data repositories and adds it to the central website.

I am not sure we need to get CI involved for this; it should be enough if we add a section `example-projects` (or so) to the docs and then either have the markdown there or just link to the datasets repositories.

**Comment by K-Meech** [comment]
@martinschorb I did the LM to EM registration in BigWarp. For the tomograms, I'm not so sure... I used the transformations from the xml files Giulia had. Perhaps ask her directly - if you're curious?

**Comment by tischi** [comment]
@martinschorb The tomograms were matched by me to the overview image using a cross-correlation based algorithm.

**Comment by martinschorb** [comment]
OK, cool how good was the initial positioning of the reconstructed volumes from my converter? The goal would be to have them more or less in position.

This extra-CC-registration would be cool to have as a tool in BDV-PG (@NicoKiaru).

**Comment by tischi** [comment]
> OK, cool how good was the initial positioning of the reconstructed volumes from my converter?

I think I ignored it, because the CC was fast enough to run on the whole image.

> This extra-CC-registration would be cool to have as a tool in BDV-PG

Absolutely!!
