### ISSUE TITLE
add annotations for all sources

### ISSUE THREAD

**Issue by martinschorb** [mobie/clem-example-project#18]
for figure 2

ping @constantinpape

**Comment by martinschorb** [comment]
the table for the tomograms already exists. We should use those IDs as well in the initial panel annotations, to have consistent colors in the two panels.

**Comment by tischi** [comment]
I am curious how this will look like in the registered overview image, because I think the annotated source display currently can only outline images that are aligned with the xyz coordinate system. Please let me know how that goes.

**Comment by constantinpape** [comment]
@tischi indeed, this doesn't wok as expected, the whole view looks very weird.
![image](https://user-images.githubusercontent.com/4263537/163142836-8fbb8694-5586-460c-bd4b-60816a2caae8.png)
You can check it out on `https://github.com/mobie/clem-example-project`, branch: `more-views` and then select `composite->lm-tomograms`. Note that it works fine without the table (`bookmarks->all_sources`).
Can you have a look?

**Comment by tischi** [comment]
And the grid view of the tomograms? Does that look normal?

**Comment by constantinpape** [comment]
> And the grid view of the tomograms? Does that look normal?

Yes, that works fine. But it also doesn't apply any transformations to map the tomograms into the global coord space.
You can check it out in `composite->highmag_tomograms`

**Comment by constantinpape** [comment]
> can you apply a `sourceTransform` to a `sourceAnnotationDisplay`?

Not in the current spec. And I think it would be a bit unclean to mix in transformations there.
But if it turns out to be the easiest solution I also wouldn't mind adding it, but I think @tischi needs to first have a look at the underlying implementation of the viewer to decide this.

**Comment by tischi** [comment]
> can you apply a sourceTransform to a sourceAnnotationDisplay?

this should not be necessary, because the code should automatically find out where the annotated sources is (including all the transformations that have been applied to the source).

**Comment by tischi** [comment]
I am having a look and this is confusing....

Could we have two views:
- `lm-tomograms`
- `lm-tomograms-with-table`

Where the only difference is that in the second one we are adding a `sourceAnnotationDisplay`?

**Comment by tischi** [comment]
@constantinpape @martinschorb 
In fact, the least work would be to just duplicate the `all-sources` view and simply add a `sourceAnnotationDisplay` for the `lm-tomograms` to it.

**Comment by constantinpape** [comment]
wait, I am on it

**Comment by martinschorb** [comment]
I would envision having  these annotations (depicting the bounds of a view) available as an option for all views already existing in a dataset.

I think, ideally there would be some way to toggle it on or off from the GUI.
Whether this internally trigger creation of an additional view, I don't mind.
However, this would mean doubling the number of views (one with the annotation and one without), this can become a problem i.e. for the `centrioles dataset`, where we already have 10.000 views.

**Comment by martinschorb** [comment]
Just think of visualizing the location of crop views inside a volume using that bbox annotation etc.

It would be super handy to simply have it as a toggle option for all views.

**Comment by martinschorb** [comment]
or better for all `imageDisplay`s

**Comment by martinschorb** [comment]
Looking into the view here again, probably the key entity we need to capture here are all the available transformed sources inside an existing view, right?

Zoom to unspaghettize the thoughts?

**Comment by constantinpape** [comment]
@tischi I have added `lm-tomograms-without-tables` for testing this. `lm-tomograms` is unchanged.

@martinschorb what you propose sounds like a major design change and has the issue that the source annotations are currently linked to the tables. For what you describe we would need to on-the-fly generate tables, which makes it difficult to add measurements etc. externally. Please note that it's already possible to toggle off the annotation tables, so I don't see why you would need to duplicate views.

**Comment by tischi** [comment]
@constantinpape Thanks. In fact, it also seems screwed up in `lm-tomograms-without-tables`:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/2157566/163342095-a63a993d-af35-4390-beab-4089af7d0950.png">

As mentioned, I think the easiest would be to add the table to the all-sources view, because there the location of the lm-tomograms is correct already.

**Comment by constantinpape** [comment]
> @constantinpape Thanks. In fact, it also seems screwed up in `lm-tomograms-without-tables`:

I see, maybe I need to double check the code that generates the view then - I was assuming that it works correctly since it should do the same thing as in `all-sources`, but maybe something is going wrong there.

> As mentioned, I think the easiest would be to add the table to the all-sources view, because there the location of the lm-tomograms is correct already.

Ok, will do so in a minute.

**Comment by martinschorb** [comment]
OK, I probably misunderstood 

> to just duplicate the `all-sources` view

as "duplicate all views that we like to annotate".

So, in the centrioles scenario this would be possible using the current implementation?

- toggle on all annotation of the sub-volume crops
- open a random full tomogram volume
- have the corresponding sub-volume boundingbox(es) shown in there
- only the box(es) from crops within that volume are shown

**Comment by constantinpape** [comment]
@tischi I added `all_sources_with_tables`. Didn't have time to check yet if this works.

**Comment by constantinpape** [comment]
> OK, I probably misunderstood
> 
> > to just duplicate the `all-sources` view
> 
> as "duplicate all views that we like to annotate".

We are just debugging here, Martin.

> So, in the centrioles scenario this would be possible using the current implementation?
> 
>     * toggle on all annotation of the sub-volume crops
> 
>     * open a random full tomogram volume
> 
>     * have the corresponding sub-volume boundingbox(es) shown in there
> 
>     * only the box(es) from crops within that volume are shown

Can you please make a separate issue about this in the tomo repo and ping us there? This is super confusing while we're trying to troubleshoot here.

**Comment by tischi** [comment]
> So, in the centrioles scenario this would be possible using the current implementation?

@martinschorb Could you please make a new issue for discussing such general ideas? Let's discuss here only what is needed to make things work for the CLEM project figure specifically.

**Comment by tischi** [comment]
(posted same time as @constantinpape ;-)

**Comment by martinschorb** [comment]
> check yet if this works

confirm, works.

**Comment by martinschorb** [comment]
for panel **A**, I would need  annotations of the `em-detail` sources as well.
 and for panel **E** the highmag tomo 38.

**Comment by tischi** [comment]
Does that look correct @martinschorb ?

It should look better than for you, because I think I managed to include the source transformations into the annotation overlay 🥳 

<img width="799" alt="image" src="https://user-images.githubusercontent.com/2157566/163345882-03589569-de36-440c-8b05-a2afb8ef1544.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/2157566/163346043-da5c1743-ed7b-4c47-9cd2-e5413cd49696.png">

**Comment by martinschorb** [comment]
true, for me there is still some misplacement of the annotations (slight rotation).

**Comment by constantinpape** [comment]
Ok, so to summarize: 
- source annotations with transformed sources work (and even improved by @tischi)
- something is wrong with how I generate the `lm-tomograms` view, I will double check this later
- we need a few more views / annotations as mentioned by @martinschorb. I will create this later and make a separate issue for this.

@tischi: I think we have most of what we need to push to MoBIE-beta, but if you still have some time today you could maybe check out https://github.com/mobie/mobie-viewer-fiji/issues/662#issuecomment-1098836524 before and also include it if it works.

**Comment by constantinpape** [comment]
Closing this in favor of #20 now since debugging works.
