### ISSUE TITLE
sourceAnnotations are not shown in image for some views

### ISSUE THREAD

**Issue by constantinpape** [mobie/clem-example-project#23]
Some of the sourceAnnotations are not shown in the `paper->Fig2_a` and `paper->Fig2_b` views:
- `Fig2_a`: `em-detail-annotations`, `fluorescence-annotations`
- `Fig2_b`: `fluorescence-annotations`

To me the spec for these views looks correct, and the viewer also navigates to the correct position when clicking on the table rows. So I am not sure what's going on here. See also the video below:

https://user-images.githubusercontent.com/4263537/166807933-05491d7a-0316-4520-ab38-f08ef853583d.mp4

**Comment by constantinpape** [comment]
Comment from @martinschorb from #20:

> could it be the combination of solid area (lm-tomos) and boundary annotations that makes trouble?
> We could simply remove the tomo annotations here (2a). Maybe that fixes it already.

I can give this a try later / tomorrow. But in general this should work...

**Comment by tischi** [comment]
Hm, weird. I saw the boundary flickering on for one short moment. I will investigate more. 

By the way: Testing from Denver Colorado, it is not as fast as from Heidelberg, but OK.

**Comment by tischi** [comment]
I think there is some bug, my guess is related to the "almost 2D" nature of the data, will check more later.

**Comment by constantinpape** [comment]
Thanks @tischi! Please ping me once you have made some progress, OR if you don't have time in the next few days so that I can look for a workaround.

> By the way: Testing from Denver Colorado, it is not as fast as from Heidelberg, but OK.

Good to know :).

**Comment by tischi** [comment]
I am now adding the voxel sizes to the intervals and then it works:

<img width="582" alt="image" src="https://user-images.githubusercontent.com/2157566/166951705-814c6a8a-df46-4248-a252-5dcc109bfdc9.png">

**Comment by tischi** [comment]
This should fix it: https://github.com/mobie/mobie-viewer-fiji/commit/607edd6bb84deb6ac8b1090e0b828efecc3a6cd1

@K-Meech Could you please update MoBIE-beta?

I can probably check again in around 10 hours from now.

**Comment by constantinpape** [comment]
Hey @K-Meech,
do you think you have a chance to release MoBIE-beta tomorrow so that we can continue checking the views and work on Fig. 2?
Thanks!

**Comment by K-Meech** [comment]
@tischi @constantinpape  - I just updated MoBIE-beta

**Comment by martinschorb** [comment]
confirm that it work in beta

**Comment by constantinpape** [comment]
Thanks @K-Meech! I just checked and the boundaries are indeed visible now.

**Comment by constantinpape** [comment]
(Martin was faster :D)
