### ISSUE TITLE
region colors

### ISSUE THREAD

**Issue by tischi** [mobie/clem-example-project#26]
Do those colors have some special meaning?

<img width="392" alt="image" src="https://user-images.githubusercontent.com/2157566/168809960-64af5590-ba21-4df3-bb32-69b0862cc36f.png">

**Comment by martinschorb** [comment]
Yes, that's the annotation boundaries in the figure panels.

**Comment by martinschorb** [comment]
As I said, all figure panels entirely done in MoBIE... Directly from data to figure all in one tool ;-)

**Comment by tischi** [comment]
just curious: for the `em-detail-annoations`, why do the first two have the same color and the third one a different color?

**Comment by martinschorb** [comment]
If you want to change the colors in the figure, just let me know your wishes. Everything is possible...

**Comment by tischi** [comment]
> If you want to change the colors in the figure, just let me know your wishes. Everything is possible...

I just want to know:  "why do the first two have the same color and the third one a different color?"
:-)
If there is no reason, I would either make all of them the same color or all of them different.

**Comment by martinschorb** [comment]
> just curious: for the `em-detail-annoations`, why do the first two have the same color and the third one a different color?

That's just a different opacity. The last one is the one we show in further detail in the following panels, that's why I made it more prominent. Dashed/dotted lines are not supported in MoBIE (and I don think we need that to be honest), so I chose opacity to distinguish them.
