### ISSUE TITLE
new figure panel

### ISSUE THREAD

**Issue by martinschorb** [mobie/clem-example-project#27]
Hi @constantinpape ,

new challenging MoBIE view, but it should work...
I like a new panel which we will put on the bottom right of Figure 2a.

it should look something like this:
![Screenshot 2022-05-18 at 08 46 52](https://user-images.githubusercontent.com/35071867/168975411-ad316ade-6fb6-4810-bec6-207e64adfcd8.png)

**Comment by martinschorb** [comment]
So it will be two crops on top of each other.

Ideally we place them right inside the view 2a (using manual transform). And then give it an annotation boundary to show where it comes from.

**Comment by martinschorb** [comment]
I'll give it a try and then might call for help...

**Comment by constantinpape** [comment]
Ok. I am mostly busy with other things until 4PM and will focus on MoBIE after that; so if there's any help you need I can take a look then.

**Comment by constantinpape** [comment]
xref https://github.com/mobie/mobie-viewer-fiji/issues/732
