### ISSUE TITLE
Takes long time until one sees anything

### ISSUE THREAD

**Issue by tischi** [mobie/clem-example-project#29]
@martinschorb @constantinpape 
Do you know the resolution pyramids for this project (especially for the 2D images)?
Loading the publication figure, for me it takes quite some time until anything appears in BDV and then it immediately is relatively high resolution...
Could we add more low resolutions to have a quicker preview?

**Comment by martinschorb** [comment]
block size is `[1024,1024,1]` all have good downsampling until less than 1 chunk per entire image. Looks good to me. No idea what takes that long to load.
Ususally there's 10-25 sources per figure. Maybe something is slowing down the compositing procedure. When you look at the log output, it reports all sources to be successfully loaded way before the viewer is ready. So to me it seems that generating the viewer takes the time and not loading the sources.

**Comment by martinschorb** [comment]
> Maybe it is not visible because the viewer transform is only set later...

Yes, the viewer trafo seems to be applied last. Maybe it therefore first loads irrelevant data.

**Comment by tischi** [comment]
I am now applying the viewer transform first and it is much better now!
