### ISSUE TITLE
RegionDisplay for a subset

### ISSUE THREAD

**Issue by tischi** [mobie/clem-example-project#31]
@constantinpape @martinschorb 

I forgot: In such a case:

- table: https://raw.githubusercontent.com/mobie/clem-example-project/main/data/hela/tables/em-detail/default.tsv
- regionDisplay: https://github.com/mobie/clem-example-project/blob/5c5e80ef13c9a9109ae7f5a811ec126fba28a2c8/data/hela/dataset.json#L2324

I guess within MoBIE we should create a table with only one row, i.e. sub-setting the table with all the rows?

**Comment by martinschorb** [comment]
Yes, if only a subset of a table is referenced, the display could be limited to that subset if this particular view is selected. However, another view could reference another subset and if the views are not exclusive, then somehow the union of subsets needs to be considered. 

In this very specific case of only one item, we could even decide to not show a table at all.

**Comment by constantinpape** [comment]
> I guess within MoBIE we should create a table with only one row, i.e. sub-setting the table with all the rows?

Yes, exactly. We just shouw the subset.

> In this very specific case of only one item, we could even decide to not show a table at all.

I wouldn't introduce any special cases for this.

**Comment by tischi** [comment]
Thank you both for the clarifications and suggestions!
I close this for now and just try to recreate the current behavior in `mobie3`.
