### ISSUE TITLE
Create mobie3 branch

### ISSUE THREAD

**Issue by tischi** [mobie/clem-example-project#32]
@constantinpape 
Could you please create a `mobie3` spec branch for this project?

**Comment by constantinpape** [comment]
Done: https://github.com/mobie/clem-example-project/pull/33

But I haven't checked yet if it actually opens, let me know if you run into any issues.

**Comment by tischi** [comment]
@martinschorb if you want to try something with MoBIE-beta and the clem-project you need to open the `mobie3` branch (not tested).

**Comment by martinschorb** [comment]
Cool, with the new updates also the registrations look good! Here's more things:
- what happened to the annotation boxes (figure views)? They are not visible for me.
- anyways, what is the status of the figure views. Is the figure order/captions in the latest manuscript (supplement as well) what will be kept for submission? If so, I will update the view names accordingly.
