### ISSUE TITLE
Suppl. Fig 1b View is not displayed correctly

### ISSUE THREAD

**Issue by constantinpape** [mobie/clem-example-project#35]
It looks like this:

![image](https://user-images.githubusercontent.com/4263537/202177283-0e1bc86d-538e-4d24-a074-949b6d1a4056.png)

But should look like this:

![image](https://user-images.githubusercontent.com/4263537/202177411-cd7346f6-b91a-4f50-8ba4-c28792ad5931.png)

So for some reason the orientation of the outer regions is wrong.
Furthermore, I selection for the regions does not work any more (i.e. I can't select any of the regions from the image or table.)

@tischi I only gave the view a quick look, but to me the metadata looks correct. Could you have a look and see if there's some bug with it in the viewer? You can open this figure via `mobie-paper->SupplFig1b`.

**Comment by martinschorb** [comment]
The same problem is present in SupplFig1a. Looks like the transformations of the `em-detail` and `fluorescence` regions are wrong/missing.

**Comment by martinschorb** [comment]
> ... Furthermore, I selection for the regions does not work any more (i.e. I can't select any of the regions from the image or table.)
> 

That works for me.

But for some reason all regions are listed twice in the tables...
![Screenshot 2022-11-16 at 20 07 18](https://user-images.githubusercontent.com/35071867/202270830-36154b1f-52f7-4b20-b0f4-c495d39c98a9.png)

**Comment by tischi** [comment]
Yes, to me it looks as if the final transformations (rotation and scaling) are only applied to the images, but not to the regions, is it? I have a suspicion why that is and will look into it (probably something wrong with the `ImageListener` for the regions).

-----

In SupplFig1a the navigation from the tables works for me.

-----

In SupplFig1a the tables look OK to me:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/2157566/202273789-0414a673-a99f-4856-8965-eb4a804ed3b7.png">

**Comment by constantinpape** [comment]
> In SupplFig1a the navigation from the tables works for me.

Ok, that also works for me now, was probably just a temporary issue.

**Comment by tischi** [comment]
I think found the issue: the mask currently just reflects the bounding box. I have to work on `public RealMaskRealInterval getMask( )` in `SpimDataImage` for the case when transformations have been applied before this method is called the first time. Will try to fix it tomorrow or Friday.

**Comment by tischi** [comment]
Fixed it: 

<img width="680" alt="image" src="https://user-images.githubusercontent.com/2157566/202382174-dc56d477-8fb5-481f-a108-d668c4201925.png">

Note that there are still some issues pending: https://imagesc.zulipchat.com/#narrow/stream/327240-ImgLib2/topic/imglib2-roi.20release

But I think for all our current use-cases I implemented a work-around.

What, e.g., would currently _not_ work is a rotated view of a well in covid-if.

**Comment by tischi** [comment]
Fix ships with `3.0.6`.

**Comment by constantinpape** [comment]
Works now with MoBIE-beta.
