### ISSUE TITLE
View for SupplFig1e is missing

### ISSUE THREAD

**Issue by constantinpape** [mobie/clem-example-project#36]
I have renamed the paper views in the project now to match the revised version. The views `SupplFig1a-d` are there now, but there wasn't a view matching `SupplFig1e` (see screenshot below). @martinschorb do you maybe have this view saved somewhere and could add it?

![image](https://user-images.githubusercontent.com/4263537/202180300-d887bf07-8d00-4c43-988e-9e57e5cf5632.png)

**Comment by martinschorb** [comment]
Can't find it. I need to check on my laptop later today. Maybe I forgot to push this commit.
