### ISSUE TITLE
SourceAnnotationTable for tomograms

### ISSUE THREAD

**Issue by constantinpape** [mobie/clem-example-project#6]
We will introduce a source annotation table, that generalizes the grid table, see https://github.com/mobie/mobie-viewer-fiji/issues/343.
We can use this here to generate a table for all the tomograms, so that they can be selected and additional tomogram information can be shown. (This will also be great for figure 2).

I am preparing another example now and we can add  this here once this works.

@martinschorb could you maybe look into making a table (csv or excel, whatever works best for you) that collects some relevant information per tomogram that we could use for this?

**Comment by tischi** [comment]
@martinschorb Giulia is now also on board! You could ask her to help with this. Does she have a github account?

**Comment by martinschorb** [comment]
@giuliamizzon

**Comment by constantinpape** [comment]
Ok, slight change of plan; I will first add the source annotation view, so that @giuliamizzon and @martinschorb can just add the annotations via the MoBIE annotator (and we can test this feature already!).
@tischi I will prepare this and let you know when I have added the source annotation view.

**Comment by constantinpape** [comment]
@tischi I have added views for the lm and hm tomograms in 99473a688ac8a4525599c34afaa89d8f842dd054.
Could you please check if these work with current MoBIE master?

**Comment by tischi** [comment]
Works!
